PageCloud/Models/SummaryReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PageCloud.Models
{
    public class SummaryReport
    {
        public UserStatistics userStatistics { get; set; }
        public ProfitSummary profit { get; set; }

    }
}

PageCloud/Controllers/GenerateReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WinForms;
using PageCloud.Models;

namespace PageCloud.Controllers
{
    public class GenerateReportsController : Controller
    {
        PageCloudEntities db = new PageCloudEntities();

        // GET: GenerateReports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserDetailReport()
        {
            List<User> users = db.Users.ToList();

            return View(users);
        }

        [HttpPost]
        public ActionResult UserDetailReport(FormCollection form)
        {
            DateTime to_date = Convert.ToDateTime(form["to_Date"].ToString());
            DateTime From_Date = Convert.ToDateTime(form["From_Date"]);

            var users = db.Users.Where(a => a.registerDate >= From_Date && a.registerDate <= to_date).ToList();

            return View(users);
        }


        public ActionResult SummaryReport()
        {
            UserStatistics userStats = new UserStatistics();
            ProfitSummary profit = new ProfitSummary();

            userStats.calculateUserStats();
            profit.CalculateGrossIncome();

            SummaryReport summary = new SummaryReport()
            {
                userStatistics = userStats,
                profit = profit
            };
            return View(summary);
        }

        public PartialViewResult AllInvoice()
        {
            List<Invoice> invoices = db.Invoices.ToList();

            return PartialView("_Invoice", invoices);
        }

        public ActionResult DetailReport(string ReportType, List<User> users)
        {
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/UserReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "UserDataSet";
            reportDataSource.Value = db.Users.Where(a => a.userRole == UserRoles.user).ToList();
            localReport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension;

            switch(reportType)
            {
                case "Word":
                    fileNameExtension = "docx";
                    break;

                case "PDF":
                    fileNameExtension = "pdf";
                    break;

                case "Excel":
                    fileNameExtension = "xlsx";
                    break;

                default:
                    fileNameExtension = "jpg";
                    break;
            }

            string[] streams;
            Warning[] warnings;
            byte[] reneredByte;



            reneredByte = localReport.Render(reportType, "", out mimeType, out encoding, out fileNameExtension, out streams, out warnings);

            Response.AddHeader("content-disposition", "attachment;filename=userReport." + fileNameExtension);

            return File(reneredByte, fileNameExtension);
        }
    }
}

PageCloud/Views/GenerateReports/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Invoices</h2>
<script src="~/Scripts/jquery-3.3.1.js"></script>


@Ajax.ActionLink("All", "All",  new AjaxOptions()
{
        HttpMethod = "GET",
        UpdateTargetId = "divInvoices",
        InsertionMode = InsertionMode.Replace 
})

<div id="divInvoices">
     
</div>

PageCloud/Views/GenerateReports/SummaryReport.cshtml
@model PageCloud.Models.SummaryReport
@{
    ViewBag.Title = "SummaryReport";
}




    <section class="wrapper">
        <div class="typo-agile">
            <h2 class="w3ls_head">Summary Report</h2>
            <div class="grid_3 grid_4 w3layouts">
                <h3 class="hdg">User Statistics</h3>
                <div class="bs-example">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.userStatistics.totalUsers)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">@Html.DisplayFor(a => a.userStatistics.totalUsers)</td>
                            </tr>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.userStatistics.totalDomains)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">@Html.DisplayFor(a => a.userStatistics.totalDomains)</td>
                            </tr>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.userStatistics.activeDomains)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">@Html.DisplayFor(a => a.userStatistics.activeDomains)</td>
                            </tr>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.userStatistics.inactiveDomains)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">@Html.DisplayFor(a => a.userStatistics.inactiveDomains)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="grid_3 grid_4 w3layouts">
                <h3 class="hdg">Profit Summary</h3>
                <div class="bs-example">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.profit.grossRegistrationIncome)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">R @Html.DisplayFor(a => a.profit.grossRegistrationIncome)</td>
                            </tr>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.profit.grossMonthlyFeeIncome)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">@Html.DisplayFor(a => a.profit.grossMonthlyFeeIncome)</td>
                            </tr>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.profit.highestSellingMonth)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">@Html.DisplayFor(a => a.profit.highestSellingMonth)</td>
                            </tr>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.profit.grossMonthSales)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">R @Html.DisplayFor(a => a.profit.grossMonthSales)</td>
                            </tr>
                            <tr>
                                <td><h4 id="h4.-bootstrap-heading">@Html.DisplayNameFor(a => a.profit.pendingPayments)<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
                                <td class="type-info">R @Html.DisplayFor(a => a.profit.pendingPayments)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </section>

PageCloud/Views/GenerateReports/UserDetailReport.cshtml
@model IEnumerable<PageCloud.Models.User>

@{
    ViewBag.Title = "UserDetailReport";
}

<h2>UserDetailReport</h2>



<div class="table-agile-info">
    <div class="panel panel-default">
        <div class="panel-heading" style="margin-bottom: 30px;">
            <b>User Report</b>

        </div>

        <div class="form-group">
            <b>Filter by date: </b>
            @using (Html.BeginForm("UserDetailReport", "GenerateReports", FormMethod.Post))
            {
                <div class="col-md-3">
                    <input type="date" name="From_Date" id="From_Date" class="form-control" required/>
                </div>

                <div class="col-md-3">
                    <input type="date" name="to_Date" id="to_Date" class="form-control" required=""/>
                </div>
                <div class="col-md-3">
                    <input type="submit" value="filter" class="btn btn-primary" />
                </div>
            }

          
        </div>
        <br />
        <div style="padding-left: 10px; margin-top: 20px;">
            @Html.ActionLink("Word", "DetailReport", new { ReportType = "Word" }) |
            @Html.ActionLink("Excel", "DetailReport", new { ReportType = "Excel" }) |
            @Html.ActionLink("PDF", "DetailReport", new { ReportType = "PDF" })

            <br />
            <b>Date of birth:</b>
            <input type="date" name="dob" id="dob" class="form-control" style="width: 150px;"/>

            <div class="table-responsive" style="margin-top: 10px;">
                <table class="table" id="tableData">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.userName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.userSurname)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.userEmail)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.registerDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.phone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.userAddress)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.city)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.postalCode)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.idno)
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.userName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.userSurname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.userEmail)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.registerDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.phone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.userAddress)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.city)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.postalCode)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.idno)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/AddOns/dataTables/js/jquery.dataTables.min.js"></script>
<script src="~/AddOns/dataTables/js/dataTables.bootstrap.min.js"></script>
<script>
    $('#tableData').dataTable();

    $(document).ready(function () {
        $.datepicker.setDefaults({
            dateFormat: 'yy-mm-dd'
        });

        $(function () {
            $('#from_date').datepicker();
            $('#to_date').datepicer();
        });

        $('#filter').click(function () {
            var from_date = $('#from_date').val();
            var to_date = $('#to_date').val();

            if (from_date != '' && to_date != '') {
                $.ajax({
                    url: "/GenerateReports/UserDetailReport",
                    method: "POST",
                    //data: (
                    //    from_date: from_date,
                    //    to_date: to_date
                    //),
                    success: function (data) {
                        $('#tableDate').html(data);
                    }
                })
            } else {
                alert("Please Select Date");
            }
        })
    })
</script>